In [1]:
from scrappers.fotmob_scrapper import FotMobScraper
player_id = "324991"  # Example player ID for testing
scraper = FotMobScraper()

bio = scraper.get_player_bio(player_id)
season_overview = scraper.get_current_season_overview(player_id)
# TODO: handle switching between leagues (WSL vs UWCL stats are different), scrape past years
season_stats = scraper.get_current_season_stats(player_id)

In [2]:
bio

,player_id,Name,Club,Height,Shirt,Birthdate,Preferred foot,Country,Primary Position
0,324991,Kim Little,Arsenal,163.0,10,1990-06-29,Right,Scotland,Defensive Midfielder

In [3]:
season_overview

stat  Goals Assists Started Matches Minutes played Rating player_id  season
value     0       1      17      18          1,385   7.17    324991    2026

In [4]:
season_stats

stat,Accurate long balls,Accurate long balls %,Accurate long balls %_per90,Accurate long balls_per90,Aerial duels won,Aerial duels won %,Aerial duels won %_per90,Aerial duels won_per90,Assists,Assists_per90,...,Touches_per90,Yellow cards,Yellow cards_per90,xG against while on pitch,xG against while on pitch_per90,xG on target (xGOT),xG on target (xGOT)_per90,player_id,season,competition
0,23,0.657,0.657,1.49,9,0.391,0.391,0.58,1,0.06,...,65.50,0,0.00,10.95,0.71,0.03,0.002,324991,2026,WSL

In [5]:
from postgres_conn import PostgresDB
db = PostgresDB()
db.connect()

In [6]:
db.save_player_fotmob_data(bio, season_overview, season_stats)
db.close()

In [7]:
teams = scraper.get_teams_from_league(9227)
teams

['https://www.fotmob.com/teams/258663/overview/everton',
 'https://www.fotmob.com/teams/231494/overview/aston-villa',
 'https://www.fotmob.com/teams/1075419/overview/london-city-lionesses',
 'https://www.fotmob.com/teams/954396/overview/manchester-united',
 'https://www.fotmob.com/teams/5811/overview/england',
 'https://www.fotmob.com/teams/231497/overview/west-ham-united',
 'https://www.fotmob.com/teams/231505/overview/brighton',
 'https://www.fotmob.com/teams/258661/overview/chelsea',
 'https://www.fotmob.com/teams/258665/overview/liverpool',
 'https://www.fotmob.com/teams/628117/overview/tottenham-hotspur',
 'https://www.fotmob.com/teams/614954/overview/leicester-city',
 'https://www.fotmob.com/teams/231488/overview/manchester-city',
 'https://www.fotmob.com/teams/258657/overview/arsenal']

In [8]:
team_player_map = {}

for team_url in teams:
    team_players = scraper.get_players_from_team(team_url)
    # store in dict: key = team_url, value = list of player IDs
    team_player_map[team_url] = team_players

In [ ]:
import pandas as pd
db = PostgresDB()
db.connect()
for player_id in team_player_map[teams[12]]:
    print(player_id)
    bio = scraper.get_player_bio(player_id)
    season_overview = scraper.get_current_season_overview(player_id)
    #season_stats = scraper.get_current_season_stats(player_id) 
    db.save_player_fotmob_data(bio, season_overview, season_stats_df=pd.DataFrame())

TypeError: list indices must be integers or slices, not tuple