In [1]:
import pandas as pd
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.common.by import By
from webdriver_manager.chrome import ChromeDriverManager
from bs4 import BeautifulSoup
import time
import re

In [2]:
from scrappers.fotmob_scrapper import FotMobScraper
player_id = "941576"  # Example player ID for testing
scraper = FotMobScraper()

bio = scraper.get_player_bio(player_id)
season_overview = scraper.get_current_season_overview(player_id)
season_stats = scraper.get_current_season_stats(player_id)
scraper.close()

In [3]:
bio

,player_id,Name,Height,Shirt,Birthdate,Preferred foot,Country,Primary Position
0,941576,Leah Williamson,170.0,6,1997-03-29,Right,England,Center-back

In [4]:
season_overview

stat  Goals Assists Started Matches Minutes played Rating player_id  season
value     1       0       2       6            233   7.69    941576    2026

In [ ]:
season_stats

Index(['Accurate long balls', 'Accurate long balls %',
       'Accurate long balls %_per90', 'Accurate long balls_per90',
       'Aerial duels won', 'Aerial duels won %', 'Aerial duels won %_per90',
       'Aerial duels won_per90', 'Assists', 'Assists_per90', 'Blocked shots',
       'Blocked shots_per90', 'Chances created', 'Chances created_per90',
       'Clean sheets', 'Clean sheets_per90', 'Clearances', 'Clearances_per90',
       'Defensive contributions', 'Defensive contributions_per90',
       'Dispossessed', 'Dispossessed_per90', 'Duels won', 'Duels won %',
       'Duels won %_per90', 'Duels won_per90', 'Expected assists (xA)',
       'Expected assists (xA)_per90', 'Expected goals (xG)',
       'Expected goals (xG)_per90', 'Fouls won', 'Fouls won_per90', 'Goals',
       'Goals conceded while on pitch', 'Goals conceded while on pitch_per90',
       'Goals_per90', 'Headed shots', 'Headed shots_per90', 'Interceptions',
       'Interceptions_per90', 'Non-penalty xG', 'Non-penalty xG_per90',
       'Recoveries', 'Recoveries_per90', 'Red cards', 'Red cards_per90',
       'Shots', 'Shots on target', 'Shots on target_per90', 'Shots_per90',
       'Successful passes', 'Successful passes %', 'Successful passes %_per90',
       'Successful passes_per90', 'Tackles', 'Tackles_per90', 'Touches',
       'Touches in opposition box', 'Touches in opposition box_per90',
       'Touches_per90', 'Yellow cards', 'Yellow cards_per90',
       'xG against while on pitch', 'xG against while on pitch_per90',
       'xG on target (xGOT)', 'xG on target (xGOT)_per90', 'player_id',
       'season'],
      dtype='str', name='stat')

In [6]:
from postgres_conn import PostgresDB
db = PostgresDB()
db.connect()

In [7]:
db.save_player_fotmob_data(bio, season_overview, season_stats)

[(941576, 2026, 1, 0.39, 0.15, 0.06, 0.25, 0.1, 2, 0.77, 1, 0.39, 0, 0.0, 0.39, 0.15, 172, 66.44, 0.815, 0.815, 18, 6.95, 0.5, 0.5, 1, 0.39, 9, 3.48, 0.6, 0.6, 2, 0.77, 0.25, 0.25, 245, 94.64, 4, 1.55, 0, 0.0, 1, 0.39, 22, 8.5, 6, 2.32, 5, 1.93, 2, 0.77, 11, 4.25, 9, 3.48, 2, 0.77, '0', '1.32', '0.00', '0.51', '1', '0.39', '0', '0.00')]