In [ ]:
from scrappers.fotmob_scrapper import FotMobScraper
player_id = "1246577"  # Example player ID for testing
scraper = FotMobScraper()

bio = scraper.get_player_bio(player_id)
season_overview = scraper.get_current_season_overview(player_id)
# TODO: handle switching between leagues (WSL vs UWCL stats are different), scrape past years
season_stats = scraper.get_current_season_stats(player_id) 
scraper.close()

In [ ]:
bio

,player_id,Name,Club,Height,Shirt,Birthdate,Preferred foot,Country,Primary Position
0,646116,Lia Wälti,Juventus,167.0,13,1993-04-19,Both,Switzerland,Central Midfielder

In [ ]:
season_overview

stat  Goals Assists Started Matches Minutes played Rating player_id  season
value     0       3      13      16          1,066   7.27    646116    2026

In [ ]:
season_stats

stat,Accurate long balls,Accurate long balls %,Accurate long balls %_per90,Accurate long balls_per90,Aerial duels won,Aerial duels won %,Aerial duels won %_per90,Aerial duels won_per90,Assists,Assists_per90,...,Expected assists (xA),Expected assists (xA)_per90,Expected goals (xG),Expected goals (xG)_per90,xG against while on pitch,xG against while on pitch_per90,xG on target (xGOT),xG on target (xGOT)_per90,player_id,season
0,33,0.635,0.635,2.79,7,0.7,0.7,0.59,3,0.25,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,646116,2026

In [ ]:
from postgres_conn import PostgresDB
db = PostgresDB()
db.connect()

In [ ]:
db.save_player_fotmob_data(bio, season_overview, season_stats)