In [1]:
import pandas as pd
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.common.by import By
from webdriver_manager.chrome import ChromeDriverManager
from bs4 import BeautifulSoup
import time
import re

In [2]:
from scrappers.fotmob_scrapper import FotMobScraper
player_id = "941576"  # Example player ID for testing
scraper = FotMobScraper()

bio = scraper.get_player_bio(player_id)
season_overview = scraper.get_current_season_overview(player_id)
season_stats = scraper.get_current_season_stats(player_id)
scraper.close()

                             stat value   type
0                           Goals     1   base
1             Expected goals (xG)  0.15   base
2             xG on target (xGOT)  0.25   base
3                  Non-penalty xG  0.15   base
4                           Shots     2   base
..                            ...   ...    ...
61                   Clean sheets  0.77  per90
62  Goals conceded while on pitch  0.00  per90
63      xG against while on pitch  0.51  per90
64                   Yellow cards  0.39  per90
65                      Red cards  0.00  per90

[66 rows x 3 columns]

In [12]:
bio

               stat            value
0              Name  Leah Williamson
1            Height           170 cm
2             Shirt                6
3      Mar 29, 1997         29 years
4    Preferred foot            Right
5           Country          England
6  Primary Position      Center-back

In [13]:
season_overview

             stat value
0           Goals     1
1         Assists     0
2         Started     2
3         Matches     6
4  Minutes played   233
5          Rating  7.69

In [ ]:
season_stats

                             stat  value   type
0                           Goals      1   base
1             Expected goals (xG)   0.15   base
2             xG on target (xGOT)   0.25   base
3                  Non-penalty xG   0.15   base
4                           Shots      2   base
5                 Shots on target      1   base
6                    Headed shots      2   base
7                         Assists      0   base
8           Expected assists (xA)   0.39   base
9               Successful passes    172   base
10            Successful passes %  81.5%   base
11            Accurate long balls     18   base
12          Accurate long balls %  50.0%   base
13                Chances created      1   base
14                      Duels won      9   base
15                    Duels won %  60.0%   base
16               Aerial duels won      2   base
17             Aerial duels won %  25.0%   base
18                        Touches    245   base
19      Touches in opposition box      4   base
20                   Dispossessed      0   base
21                      Fouls won      1   base
22        Defensive contributions     22   base
23                        Tackles      6   base
24                  Interceptions      5   base
25                  Blocked shots      2   base
26                     Recoveries     11   base
27                     Clearances      9   base
28                   Clean sheets      2   base
29  Goals conceded while on pitch      0   base
30      xG against while on pitch   1.32   base
31                   Yellow cards      1   base
32                      Red cards      0   base
33                          Goals   0.39  per90
34            Expected goals (xG)   0.06  per90
35            xG on target (xGOT)   0.10  per90
36                 Non-penalty xG   0.06  per90
37                          Shots   0.77  per90
38                Shots on target   0.39  per90
39                   Headed shots   0.77  per90
40                        Assists   0.00  per90
41          Expected assists (xA)   0.15  per90
42              Successful passes  66.44  per90
43            Successful passes %  81.5%  per90
44            Accurate long balls   6.95  per90
45          Accurate long balls %  50.0%  per90
46                Chances created   0.39  per90
47                      Duels won   3.48  per90
48                    Duels won %  60.0%  per90
49               Aerial duels won   0.77  per90
50             Aerial duels won %  25.0%  per90
51                        Touches  94.64  per90
52      Touches in opposition box   1.55  per90
53                   Dispossessed   0.00  per90
54                      Fouls won   0.39  per90
55        Defensive contributions   8.50  per90
56                        Tackles   2.32  per90
57                  Interceptions   1.93  per90
58                  Blocked shots   0.77  per90
59                     Recoveries   4.25  per90
60                     Clearances   3.48  per90
61                   Clean sheets   0.77  per90
62  Goals conceded while on pitch   0.00  per90
63      xG against while on pitch   0.51  per90
64                   Yellow cards   0.39  per90
65                      Red cards   0.00  per90